#ifndef __OutOfSpace_EnginenewStageDialog__
#define __OutOfSpace_EnginenewStageDialog__

/**
@file
Subclass of newStageDialog, which is generated by wxFormBuilder.
*/

#include "OOS3D_Engine.h"

//// end generated include

/** Implementing newStageDialog */
class OOS3D_newStageDialog : public newStageDialog
{
	public:
		/** Constructor */
		OOS3D_newStageDialog( wxWindow* parent );
	//// end generated class members

};

#endif // __OutOfSpace_EnginenewStageDialog__
