#ifndef __OutOfSpace_EngineaddActorDialog__
#define __OutOfSpace_EngineaddActorDialog__

/**
@file
Subclass of addActorDialog, which is generated by wxFormBuilder.
*/

#include "OOS3D_Engine.h"

//// end generated include

#define ADDACTOR_EXIT_STATUS_CANCEL   0
#define ADDACTOR_EXIT_STATUS_OK       1

/** Implementing addActorDialog */
class OOS3D_addActorDialog : public addActorDialog
{
	protected:
		// Handlers for addActorDialog events.
		void OnCancelButtonClick( wxCommandEvent& event );
		void OnAddActorButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		OOS3D_addActorDialog( wxWindow* parent );

		void addModel(wxString model_option); //will also add to hitbox
		void addTexture(wxString texture_option);

		wxString actor_id;
		wxString model;
		wxString hitbox;
		wxString texture;

		int model_index;
		int hitbox_index;
		int texture_index;

		int exit_status;
	//// end generated class members

};

#endif // __OutOfSpace_EngineaddActorDialog__
