#ifndef __OutOfSpace_EngineOOS3D_Engine__
#define __OutOfSpace_EngineOOS3D_Engine__

/**
@file
Subclass of OOS3D_Engine, which is generated by wxFormBuilder.
*/

#include "OOS3D_Engine.h"

//// end generated include

/** Implementing OOS3D_Engine */
class OOS3D_Engine_Frame : public OOS3D_Engine
{
	protected:
		// Handlers for OOS3D_Engine events.
		void OnNewProjectMenuSelect( wxCommandEvent& event );
		void OnLoadProjectMenuSelect( wxCommandEvent& event );
		void OnSaveProjectMenuSelect( wxCommandEvent& event );
		void OnExitMenuSelect( wxCommandEvent& event );
	public:
		/** Constructor */
		OOS3D_Engine_Frame( wxWindow* parent );
	//// end generated class members

};

#endif // __OutOfSpace_EngineOOS3D_Engine__
