#ifndef __OutOfSpace_EnginenewStageDialog__
#define __OutOfSpace_EnginenewStageDialog__

/**
@file
Subclass of newStageDialog, which is generated by wxFormBuilder.
*/

#include "OOS3D_Engine.h"

//// end generated include

#define NEWSTAGE_EXIT_STATUS_CANCEL   0
#define NEWSTAGE_EXIT_STATUS_OK       1

#define NEWSTAGE_TYPE_3D 0
#define NEWSTAGE_TYPE_2D 1

/** Implementing newStageDialog */
class OOS3D_newStageDialog : public newStageDialog
{
	public:
		/** Constructor */
		OOS3D_newStageDialog( wxWindow* parent );

		void OnCancelButtonClick( wxCommandEvent& event );
		void OnOKButtonClick( wxCommandEvent& event );

		wxString stage_name;
		int stage_type = 0;
		int exit_status;
	//// end generated class members

};

#endif // __OutOfSpace_EnginenewStageDialog__
