#ifndef __OutOfSpace_EngineOOS3D_Engine__
#define __OutOfSpace_EngineOOS3D_Engine__

/**
@file
Subclass of OOS3D_Engine, which is generated by wxFormBuilder.
*/

#include "OOS3D_Engine.h"
#include "OOS3D_Project_Structures.h"
//// end generated include

/** Implementing OOS3D_Engine */
class OOS3D_Engine_Frame : public OOS3D_Engine
{
	protected:
		// Handlers for OOS3D_Engine events.
		void OnNewProjectMenuSelect( wxCommandEvent& event );
		void OnLoadProjectMenuSelect( wxCommandEvent& event );
		void OnSaveProjectMenuSelect( wxCommandEvent& event );
		void OnExitMenuSelect( wxCommandEvent& event );
	public:
		/** Constructor */
		OOS3D_Engine_Frame( wxWindow* parent );

		void SetupProjectTree();
		OOS3D_Project* game_project;

		//SetupTestProject
		void SetupTestProject();

		wxString app_path;

		wxImageList* project_tree_imageList;
		int project_tree_rootImage;
        int project_tree_folderImage;
        int project_tree_fileImage;

        int ClientH(float pct) { return (int) (GetClientSize().y * pct / 100); }
		int ClientW(float pct) { return (int) (GetClientSize().x * pct / 100); }

	//// end generated class members

};

#endif // __OutOfSpace_EngineOOS3D_Engine__
