#ifndef __OutOfSpace_EnginenewProjectDialog__
#define __OutOfSpace_EnginenewProjectDialog__

/**
@file
Subclass of newProjectDialog, which is generated by wxFormBuilder.
*/

#include "OOS3D_Engine.h"

//// end generated include

/** Implementing newProjectDialog */
class OOS3D_newProjectDialog : public newProjectDialog
{
	public:
		/** Constructor */
		OOS3D_newProjectDialog( wxWindow* parent );

		void OnCancelButtonClick( wxCommandEvent& event );
		void OnOKButtonClick( wxCommandEvent& event );

		wxString project_name;
	//// end generated class members

};

#endif // __OutOfSpace_EnginenewProjectDialog__
